services:

#------------------------>PROMETHEUS<------------------------------------------------------------
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: unless-stopped

    ports:
      - "9090:9090"

    volumes:
      - ../configs/prometheus:/etc/prometheus
      - ../data/prometheus:/prometheus

    networks:
      - monitoring

#------------------------------------>GRAFANA<-----------------------------------------------
  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - ../data/grafana:/var/lib/grafana

    networks:
      - monitoring

#---------------------------------------->SNMP-EXPORTER<------------------------------------
  snmp-exporter:
    image: prom/snmp-exporter:v0.29.0
    container_name: snmp-exporter
    restart: unless-stopped

    ports:
      - "9116:9116"

    volumes:
      - ../configs/snmp_exporter:/etc/snmp_exporter

    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"

    networks:
      - monitoring


#-------------------------------------->SNMP-GENERATOR<------------------------------------
  snmp-generator:
    image: prom/snmp-generator:v0.29.0
    container_name: snmp-generator

    volumes:
      - ../configs/snmp-generator:/opt/snmp-generator

    working_dir: /opt/snmp-generator

    stdin_open: true
    tty: true

    networks:
      - monitoring




#
#
#
#++++++++++++++++++++++++++++++++++++++++++-----REDES-----++++++++++++++++++++++++++++++++++++
networks:

  monitoring:
    driver: bridge
